version: '3'
services:
  postgresql:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mysql5.7:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    sysctls:
      - net.core.somaxconn=1024
    command: redis-server --appendonly yes
  activemq:
    image: rmohr/activemq
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./activemq/data:/opt/activemq/data